name: GuBu-Service CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['GuBu-Service CI']
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Ubuntu
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PEMKEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Load nvm and node environment
            export NVM_DIR="/home/ubuntu/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            cd /home/ubuntu/8JO/gubu_service

            git switch main

            git pull

            echo "${{ secrets.SERVER_ENV }}" > .env

            npm ci

            npm run build

            pm2 delete gubu-service || true

            pm2 start dist/main.js --name gubu-service

            pm2 save
