name: GuBu CI

on:
  workflow_dispatch:
  push:
    branches: [dev, main]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [dev, main]

jobs:
  ci-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
#      - name: Run test # step의 이름 지정 (선택 사항)
#        run: |
#          yarn test
#           npm run test


## Ci 수정 ( 브랜치 )